---
  HostInfos: 
    - &host http://nutricalc.local/
    - &projectname nutricalc
  Host:
    - HOST:
      - "212.47.245.96"
    - DB_NAME:
      - nutricalc
    - USERNAME:
      - nutridev
    - PWD:
      - nutridev
...