---
  Constants: 
    - &host http://nutricalc.local/
    - &local ../src/
    - &view View/
    - &model Model/
    - &assets assets/
    - &index index.php/
  Asset:
    - JS:
      - *host
      - *assets
      - js/
    - CSS:
      - *host
      - *assets
      - css/
    - IMG:
      - *host
      - *assets
      - img/
  View:
    - VIEW:
      - *view
    - ELEMENT:
      - *local
      - *view
      - element/
    - ACCOUNT:
      - *local
      - *view
      - account/
    - TEMPLATE:
      - *local
      - *view
      - template/
    - WEIGHT_TRACKING:
      - *local
      - *view
      - weightTracking/
    - ERROR:
      - *local
      - *view
      - error/
    - TRAINING:
      - *local
      - *view
      - training/
    - SETTING:
      - *local
      - *view
      - settings/
    - USER:
      - *local
      - *view
      - user/
  Route:
    - APP:
      - *host
      - *index
      - app/
    - API:
      - *host
      - *index
      - api/
  Model:
    - MODEL:
      - *local
      - Model/
    - REPOSITORY:
      - *local
      - *model
      - Repository/
    - ENTITY:
      - *local
      - *model
      - Entity/

...